#!/bin/sh

PRE_STOP_LOG_ROLE="${PRE_STOP_LOG_ROLE:-waiter}"
. "$(dirname "$0")/termination-env"

{

log "The hook has started: %s" \
  "$(parameters_string \
    "marker_file" \
    "heartbeat_file" \
    "bailout_file" \
    "recheck_sleep" \
    "report_every" \
  )"

n=0
checks_started=$(date +%s)

while [ ! -f "$marker_file" ]; do
  check_bailout
  check_heartbeat "$checks_started"

  if [ $((n % report_every)) -eq 0 ]; then
    log "Waiting for the marker file to be accessible..."
  fi

  n=$((n + 1))
  sleep "$recheck_sleep"
done

wait_duration=$(( $(date +%s) - checks_started ))
log "The marker file found after %ss, exiting to proceed to termination" "$wait_duration"

} > "$stdout" 2> "$stderr"
