---

name: Devel

on:
  push:
    branches: [devel]

jobs:
  push-development-images:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout ascender-operator
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          repository: ${{ github.repository_owner }}/ascender-operator
          path: ascender-operator

      - name: Install playbook dependencies
        run: |
          python3 -m pip install docker

      - name: Log into registry ghcr.io
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121  # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get current date
        id: date
        uses: Kaven-Universe/github-action-current-date-time@7c1d8465d1bfd7d35466d2ee82a8e460780561ae  # v1.5.0

      - uses: benjlevesque/short-sha@dbe07338b37c456ce06d23409b35a56a7815eef4  # v4.0
        id: short-sha
        with:
          length: 6

      - name: Push ascender-operator image to development registry
        working-directory: ascender-operator
        run: |
          BUILD_ARGS="--build-arg DEFAULT_AWX_VERSION=latest \
              --build-arg OPERATOR_VERSION=${{ steps.date.outputs.day }}+git${{ steps.short-sha.outputs.sha }}" \
          IMG=ghcr.io/${{ github.repository }}_devel:${{ steps.date.outputs.day }}+git${{ steps.short-sha.outputs.sha }} \
          make docker-buildx
