---
name: Promote Ascender Operator image
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Name for the tag of the release.'
        required: true

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - name: Set GitHub Env vars for workflow_dispatch event
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "TAG_NAME=${{ github.event.inputs.tag_name }}" >> $GITHUB_ENV

      - name: Set GitHub Env vars if release event
        if: ${{ github.event_name == 'release' }}
        run: |
          echo "TAG_NAME=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          depth: 0

      - name: Log into registry ghcr.io
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121  # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Tagged Staged Image and Publish to ghcr.io
        run: |
          docker buildx imagetools create \
            ghcr.io/${{ github.repository }}:${{ env.TAG_NAME }} \
            --tag ghcr.io/${{ github.repository }}:${{ env.TAG_NAME }}

      - name: Pull Staged Image and Publish to ghcr.io/${{ github.repository }}:latest
        run: |
          docker buildx imagetools create \
            ghcr.io/${{ github.repository }}:${{ env.TAG_NAME }} \
            --tag ghcr.io/${{ github.repository }}:latest
